export const ChartColor = {
  bgGrey: '#f6f6f6',
  bgWhiteGrey: '#fdfdfd',
  bgLightGrey: '#ececec',
  bgDarkGrey: '#777',
  bgMelonGreen: '#36BF29',
  bgDisabledGrey: '#D9D9D9',
  borderGrey: '#d9d9d9',
  textBlack: '#000',
  textWhite: '#fff',
  textWhiteGrey: '#fdfdfd',
  textLightGrey: '#b0b0b0',
  textGrey: '#777',
  isedolPink: '#ea4476',
  textBlue: '#69A1F8',
}
